Add correct list of dependency packages for perftest
linux-rdma/perftest pull request #303
Opened 2024-12-19 11:54 UTC by TamaraBabayan

While creating .deb and .rpm packages for perftest, some dependencies for proper operation are missing. This patch adds the correct list of minimum required packages that include all the necessary libraries for perftest to function successfully.

For rpm package was added the following list of dependencies`
`libibverbs, libibumad, librdmacm, libpci3, rdma-core`

For deb package was added `libibumad` and` rdma-core`, which were missing.

2025-01-05 13:12 UTC, tzafrir-mellanox requested changes

2025-01-05 13:12 UTC, tzafrir-mellanox commented on perftest.spec
> +Requires:       libibverbs libibumad librdmacm libpci3 rdma-core
See other comment: dependencies on libraries should be auto-generated. Dependency on rdma-core: why?

2025-01-15 08:57 UTC, TamaraBabayan commented on debian/control
> +Depends: ${shlibs:Depends}, ${misc:Depends}, libibverbs1 (>= 1.1.6), librdmacm1 (>=1.0.8), libibumad, rdma-core
We reviewed the section on automatically adding the library libibumad and agree that it is added automatically. The issue we encountered was that the library was not added automatically when it was not already installed on the system. It is only added if it is present on the system as an installed package. 
Thank you, indeed, an explicit dependency is not required. The issue we were trying to resolve was in our build environment and the installed packages. We rechecked and confirmed that the automatic output is working.

2025-01-15 08:59 UTC, TamaraBabayan commented on perftest.spec
> +Requires:       libibverbs libibumad librdmacm libpci3 rdma-core
Thank you. We have checked the automatic addition of libraries, and everything is working. The addition of rdma-core was needed only in our environment, so it is not needed here.

2025-01-15 09:34 UTC, tzafrir-mellanox commented on debian/control
> +Depends: ${shlibs:Depends}, ${misc:Depends}, libibverbs1 (>= 1.1.6), librdmacm1 (>=1.0.8), libibumad, rdma-core
I believe that you are right that the dependency on rdma-core is missing. The dependency on "libibumad" is incorrect (and if it were correct, it should have been added automatically). So please remove it. 

FTR: on my system (Debian Testing) the package depends on:   ibverbs-providers (>= 37), libc6 (>= 2.34), libibumad3 (>= 1.3.9), libibverbs1 (>= 34), libpci3 (>= 1:3.8.0), librdmacm1t64 (>= 1.0.19)   and all of those seem to be automatic.

On the debian packaging, debian/control has only "Depends: ${shlibs:Depends}, ${misc:Depends}". However, as you mention, I guess that rdma-core is probably also needed.

2025-01-15 11:13 UTC, TamaraBabayan commented on debian/control
> +Depends: ${shlibs:Depends}, ${misc:Depends}, libibverbs1 (>= 1.1.6), librdmacm1 (>=1.0.8), libibumad, rdma-core
Yes, I can add only rdma-core, but why do you think it is needed? We looked into it, and indeed the tests can be run without the rdma-core package.

2025-01-15 15:10 UTC, bdrung commented on debian/control
> +Depends: ${shlibs:Depends}, ${misc:Depends}, libibverbs1 (>= 1.1.6), librdmacm1 (>=1.0.8), libibumad, rdma-core
I am against this change to the Debian packaging. Instead I propose to even drop the other hard-coded dependencies: https://github.com/linux-rdma/perftest/pull/307

2025-02-06 06:41 UTC, TamaraBabayan commented on debian/control
> +Depends: ${shlibs:Depends}, ${misc:Depends}, libibverbs1 (>= 1.1.6), librdmacm1 (>=1.0.8), libibumad, rdma-core
Thank you for answer.

2025-02-06 06:41 UTC, closed without merging