Add ipv6 address support for initial communication.
linux-rdma/perftest pull request #92
Opened 2020-06-19 08:10 UTC by dmonakhov

Currenty initial negotiation performed via ipv4 which is not suitable for modern ipv6 only topology
This patch allow to specify which address family to use, default behaviour not changed.

New option:  --ipv6-addr

Usage example:
# Server
./ib_write_bw -d mlx5_0 --ipv6-addr
# Client
./ib_write_bw -d mlx5_0 --ipv6-addr 2a02:6b8:c0e:97f:0:441d:9fbd:3f1e

2020-06-20 07:20 UTC, dmonakhov commented
Last commit  is redundant, maintainer should  update changelog by himself ( commands described in commit message)

2020-06-29 11:29 UTC, dimasique1 commented
Hi @dmonakhov,

It would take more time to review and testing the code from my side, sorry for delayed merge. Thank you for the contribution.

2020-07-01 11:10 UTC, dmonakhov commented
I've fixed some mistakes in debian build config. Now debian package build works w/o crunches.

2021-02-19 14:15 UTC, alokprasad commented
@dmonakhov  which tag it is available in pertest

2021-02-19 15:23 UTC, alokprasad approved these changes

2021-02-19 15:42 UTC, alokprasad commented
With latest rdma-core you have to remove 
#ifdef HAVE_GID_TYPE
// declaration is copied from rdma-core, since it is private there.
enum ibv_gid_type
{
        IBV_GID_TYPE_IB_ROCE_V1,
        IBV_GID_TYPE_ROCE_V2,
};
and also modify 

struct roce_version_sorted_enum roce_versions_sorted[] = {
        {IBV_GID_TYPE_ROCE_V1, 1},
        {IBV_GID_TYPE_ROCE_V2, 2},
};

2021-02-21 01:46 UTC, alokprasad commented
Getting error
 Found Incompatibility issue with GID types.
 Please Try to use a different IP version

Also will be good to hav working with rdma_cm

2022-04-28 13:57 UTC, HassanKhadour requested changes
those debian packaging changes should be in a different pull request
Please exclude them from this pull request

2022-04-28 13:59 UTC, dmonakhov commented
Ok, will do.

2022-08-10 07:36 UTC, sshaulnv commented
Hi @dmonakhov,
have you had a chance to work on it?

2022-08-15 12:04 UTC, HassanKhadour commented
Can one of the admins verify this patch?

2022-08-15 14:06 UTC, dmonakhov commented
Sorry, missed this notification. No issue is not resolved yet.  I'll try to fix  it this week.

2022-11-10 09:01 UTC, HassanKhadour commented
Hi dmonakhov,
any update?

2022-11-11 10:01 UTC, dmonakhov commented
Hi, 
Sorry for delay. I've quit my job so I do not have access to infiniband hardware at the  moment, so I can not test my stuff.
But the good new is that I will probably have access to EFA devices soon so I'll be back to actual rebase.

2023-06-27 22:45 UTC, joyom-msft commented on src/perftest_resources.c
> +	case AF_INET6:  ((struct sockaddr_in6*) sin)->sin6_port = htons(port);
needs to add break statements to avoid falling through to the default section and always returning failure

2023-06-27 22:52 UTC, xiakun-microsoft commented on src/perftest_communication.c
> +	struct sockaddr sin;
here is a bug, you can't define a `struct sockaddr` variable to save the ipv6 address. `rdma_bind_addr()` fails with the current change.
change it to `struct sockaddr *sin`, and point it to `res->ai_addr`, no need to copy the values.
also it looks line 1083 (sockaddr_set_port) is not necessary as `check_add_port` already assigns the port.

2023-06-27 22:52 UTC, xiakun-microsoft commented on src/perftest_communication.c
> +	struct sockaddr sin;
`rdma_client_connect()` has the same bug.

2023-06-28 00:45 UTC, xiakun-microsoft commented on src/perftest_communication.c
> +	struct sockaddr sin;
use `struct sockaddr_storage`

2023-06-28 07:07 UTC, HassanKhadour commented
@xiakun-microsoft @joyom-msft , thanks for the assist guys!, you were very helpful.
 I followed below note
"here is a bug, you can't define a struct sockaddr variable to save the ipv6 address. rdma_bind_addr() fails with the current change.
change it to struct sockaddr *sin, and point it to res->ai_addr, no need to copy the values."
on server and client parts and it solved the issue.

I didn't understand this note "use struct sockaddr_storage" much, can you please describe it more? I just switched "struct sockaddr sin" to be a pointer and it worked fine

2023-06-28 16:12 UTC, xiakun-microsoft commented
> @xiakun-microsoft @joyom-msft , thanks for the assist guys!, you were very helpful. I followed below note "here is a bug, you can't define a struct sockaddr variable to save the ipv6 address. rdma_bind_addr() fails with the current change. change it to struct sockaddr *sin, and point it to res->ai_addr, no need to copy the values." on server and client parts and it solved the issue.
> 
> I didn't understand this note "use struct sockaddr_storage" much, can you please describe it more? I just switched "struct sockaddr sin" to be a pointer and it worked fine

Sorry I didn't make it clear.
My teammate @joyom-msft rebased this PR on the master branch, and a new local variable `struct sockaddr_in source_sin;` was added on the master branch. I guess the purpose of that variable is to keep a copy of source address, so suggested using `struct sockaddr_storage` which has enough space for the ipv6 address.

2023-07-02 09:22 UTC, HassanKhadour commented
@dmonakhov Following the priority of this feature that has been raised from several perftest users and following the priority we created a new PR based on this PR that includes the requested changes that may solve all the commits of PR, RDMA CM issue was fixed with @xiakun-microsoft and @joyom-msft assist.
@dmonakhov @xiakun-microsoft @joyom-msft Appreciate your review here https://github.com/linux-rdma/perftest/pull/218

2023-07-02 10:40 UTC, dmonakhov commented
@xiakun-microsoft Thank you very much for moving this forward, your PR is looks good, probably we can close this one it favor to  https://github.com/linux-rdma/perftest/pull/218

2023-07-11 16:13 UTC, closed without merging